// <auto-generated />
using System;
using IncomeTaxCalculator.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncomeTaxCalculator.Persistence.Migrations
{
    [DbContext(typeof(IncomeTaxDbContext))]
    partial class IncomeTaxDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncomeTaxCalculator.Persistence.Entities.TaxBand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AnnualSalaryLowerLimit")
                        .HasColumnType("int");

                    b.Property<int?>("AnnualSalaryUpperLimit")
                        .HasColumnType("int");

                    b.Property<int>("TaxRate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxBands");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb49c25c-f1e2-4659-8420-c24eab2805cd"),
                            AnnualSalaryLowerLimit = 0,
                            AnnualSalaryUpperLimit = 5000,
                            TaxRate = 0
                        },
                        new
                        {
                            Id = new Guid("f0ef7fde-4baf-497b-bae6-faf72e4427a2"),
                            AnnualSalaryLowerLimit = 5000,
                            AnnualSalaryUpperLimit = 20000,
                            TaxRate = 20
                        },
                        new
                        {
                            Id = new Guid("c65fad47-6d23-425b-a0f8-a62ae584c111"),
                            AnnualSalaryLowerLimit = 20000,
                            TaxRate = 40
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
